export default {
  Fire: 'fire',
  Nature: 'nature',
  Light: 'light',
  Earth: 'earth',

  Basic: 'Basic',
  Advanced: 'Advanced',
  Elite: 'Elite',
  Ultimate: 'Ultimate',

  Zenron: 'zenron',
  Jane: 'jane',
  Thoben: 'thoben',
  Tierra: 'tierra',
  Myris: 'myris',
  Asgard: 'asgard',
  VanRaven: 'vanRaven',
  Ray: 'ray',
  Lua: 'lua',

  Damagespell: 'damageSpell',
  ShieldSpell: 'shieldSpell',
  HealSpell: 'healSpell',
  OvertimeSpell: 'overtimeSpell',

  Instant: 'Instant',
  Fast: 'Fast',
  Normal: 'Nnormal',
  Slow: 'Slow',

  Self: 'self',
  Enemy: 'enemy',
  AllPlayers: 'allPlayers',

  Arena1: 'one',
  Arena2: 'two',
  Arena3: 'three',
  Arena4: 'four',
  Arena5: 'five',
  Arena6: 'six',
  Arena7: 'seven',
  Arena8: 'eight',
  Arena9: 'nine',
  Arena10: 'ten',
}
